### ISSUE TITLE
Unable to get any output from status.sh

### ISSUE THREAD

**Issue by slink007** [andresgongora/synth-shell#128]
When I run the status.sh script I get no output of any sort.  No picture, no text, no errors - I only see what I assume are a couple of new lines as my prompt is moved down the screen a bit after the script runs.  I am using the default status.config file as it came to me with no modifications.

I see this if ~/.bashrc calls the script or if I call it directly myself.

My OS is SparkyLinux which is essentially Debian "Buster".  My desktop is XFCE4.  For what it's worth the fancy bash prompt is working wonderfully.

**Comment by andresgongora** [comment]
That's a very weird problem.
Could you please post the output of running the following commands in the terminal (simply copy and paste the commands, then send their output over here):

- `echo "This message was printed with echo"`
- `printf "This message was printed with printf\n"`
- `echo "My bash is: $BASH_VERSION"`
- `bash --version`

Let's make sure that your terminal emulator can print messages using the functions that are most commonly found inside the script, and that you are running a compatible version of bash (I had never compatibility issues, but you never know.)

**Also, very important**: please make sure that when installing the script, in the step where you _clone the git repository_, you are doing so _recursively_; as this repo contains submodules. That is: `git clone --recursive https://github.com/andresgongora/synth-shell.git` (note the --recursive).

Just in case, run this one-liner to see what happens (when prompted, just press enter over and over again):

`git clone --recursive https://github.com/andresgongora/synth-shell.git && chmod +x synth-shell/setup.sh && synth-shell/setup.sh  && rm -fr synth-shell && bash && source ~/.bashrc`

**Comment by slink007** [comment]
steve  gptest1  ~  echo "This message was printed with echo"
This message was printed with echo

 steve  gptest1  ~  printf "This message was printed with printf\n"
This message was printed with printf

 steve  gptest1  ~  echo "My bash is: $BASH_VERSION"
My bash is: 5.0.3(1)-release

 steve  gptest1  ~  bash --version
GNU bash, version 5.0.3(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

 steve  gptest1  ~ 

**Comment by slink007** [comment]
I'm now seeing different, and better, behavior than what I saw yesterday.  If I launch a brand new instance of my terminal I get the exact same behavior as described in OP.  However, if I directly call the script after the terminal is launched, or if I open up a new tab in my terminal emulator, the script works OK apart from my text overwriting the left side of my image.

The attached image is what I get when directly calling the script now (external IP address edited out).

![Screenshot_2019-07-18_09-27-20](https://user-images.githubusercontent.com/41128914/61462409-9a1b6b00-a940-11e9-8b09-c1be81dc295f.png)

**Comment by slink007** [comment]
I don't know why but things have changed a bit.  If I launch a brand new terminal I still get the same behavior as described in OP.  Yet sometimes when I directly call the script it mostly works (see attached image where I've edited out my external IP).  If I close the terminal out and open up a new one then I'm right back to the OP again.

![Screenshot_2019-07-18_09-27-20](https://user-images.githubusercontent.com/41128914/61463305-1ebab900-a942-11e9-967f-c5c1dce38bad.png)

**Comment by olmari** [comment]
AFAIK latter is what you should see in the first place, cutting into logo is then because GPU string is so long, and for "failsafe" we cut into logo rather than miss out info.. So why ins't it working from bashrc is needed to solve, rest of that look is a) more regex for GPU string to shorten it and b) tweaking configs for yourself, both separate things themselves.

**Comment by andresgongora** [comment]
As for the cut logo, olmari is completely right. Don't worry about that, I'm adding a quick fix for your aprticular GPU (I will push it to the develop branch for now).

I'm surprised, however, by the weird behavior of your bashrc file. It appears to me, with the data we have know, that said file is not sourced; or that it's execution halts prematurely. While I fix the GPU, could you please try the following (I don't know your level of expertise, so I'll stay on the safe side during the following explanation):

1. Open your `bashrc` file. To do so, use any editor you want (I will assume you have nano, but replace it with gedit, etc. if you want): `nano ~/.bashrc`

2. Add the following line at the beginning of your file: `echo "Start of bashrc"`

3. Add this at the end of the file, after the call of all other scripts in synth-shell: `echo "End of bashrc"`

4. Save the file (in nano, it's ctrl+o, then ctrl+x to close)

5. Open a completely new terminal. Confirm that _start of bashrc_ and _end of bashrc_ was printed in said terminal. Scroll up if need be

This should confirm whether the `bashrc` file is executed from beginning to end; because if you can run `status.sh` manually, but not when opening a terminal, the problem might lay here. If it does not seem to work and you don't mind, please post the content's of your `bashrc` file. I'll try to replicate the problem on my PC.

**Comment by andresgongora** [comment]
@slink007 GPU problem fixed in c2f7b4a . Once we have everything sorted out, I will push a hotfix to the master branch. 

Also, pelase confirm whether you censored your external IP from the above screenshot (that's the recommended behaviour), or whether you did not get the IP. The thing is, if you did not censor the IP, something weird is going on, because @olmari implemented extreme redundancy to get the IP even under the most unfavorable of conditions.

Other than that, your bash version (5.0.3) is newer than mine (5.0.2), but I don't think that's the problem.

**Comment by slink007** [comment]
Re bashrc:  I put the statements into the file as directed, saved the file, closed the terminal, and opened up a new instance.  I got the **End of bashrc** message but found I could not scroll up to see the starting message.

Re IP address:  Yes, I edited the screen capture to remove the information myself.

**Comment by andresgongora** [comment]
That's weird... and interesting. For some reason it appears that you are either loosing part of your terminal output, or that (I'm purely speculating here) have a nested bash session inside the terminal. What happens when you type `exit` inside the terminal, does the window close completely?

I gather that `clear` and all other similar commands are not shadowed by any alias, right?

Re IP: oh good! You did such a great job masking it that it appeared as part of your background image hehehehe

In any case, I'm very confused as for the cause of your issue. So far we've tested the script in most flavors of ArchLinux and Debian with no major issue.

**Comment by andresgongora** [comment]
I just saw your edit. `status.sh` calls `clear` at least once to cleanup the terminal before printing. This was needed to reset the cursor to a "safe" position, but I think it should be safe to remove now AFAIK.... done in ad08fb0 . Could you please install the develop version?: `git clone --recursive --single-branch --branch develop https://github.com/andresgongora/synth-shell.git && chmod +x synth-shell/setup.sh && synth-shell/setup.sh  && rm -fr synth-shell && bash && source ~/.bashrc`

And just to be sure of everything. Can you check that your `bashrc` file contains no call to `reset`?

**Comment by slink007** [comment]
Doing `grep reset ~/.bashrc` does not yield any results so I think we're good there.

After installing the suggested version when I open a terminal now I see both `Start of bashrc` and `End of bashrc` messages but in-between I only find a couple of empty lines.

**Comment by slink007** [comment]
At a loss?  

> And just to be sure of everything. Can you check that your bashrc file contains no call to reset?

Using grep to scan that file for reset, and not finding it, proves that there is no call to reset in there.  What, should I manually go through the file line-by-line instead?

**Comment by slink007** [comment]
I made the changes to `crit_cpu_percent` and `crit_ram_percent`.  When I open a new terminal, or when I directly call the script, I get;
`

SYSTEM LOAD:   3.1 us   6.2 sy   0.0 ni  90.6 id  
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
 2312 root      20   0  591088  76928  46608 S   6.2   2.0   0:04.05 Xorg
 2513 steve     20   0  539992  36720  29644 S   6.2   0.9   0:00.37 panel-1-p+
 2517 steve     20   0  218984  27160  22104 S   6.2   0.7   0:00.13 panel-2-b+

MEMORY:	 Only 3152 MB of RAM available!!
    %	 SIZE	  PID	COMMANDD
  1.9    81MB    2312	/usr/lib/xorg/Xorg
  1.5    53MB    2548	/usr/bin/python3
  1.1    39MB    2511	nm-applet

`

**Comment by slink007** [comment]
With the first printf experiment I got the word "World" followed by a newline.

With the second printf experiment I got the word "World" automatically when I opened a new terminal.

**Comment by andresgongora** [comment]
> With the first printf experiment I got the word "World" followed by a newline.
> 
> With the second printf experiment I got the word "World" automatically when I opened a new terminal.

Great. It seems it's working.
Not so great. It's working... that means that it's not the problem.

Please edit your bashrc file such that it only contains:
```
[[ $- != *i* ]] && return
echo "start of bashrc"
source /home/steve/.config/synth-shell/status.sh
echo "end of bashrc"
```
With what we know so far, that should work flawlessly.

> BTW, changing those critical levels reveals a very minor bug. You don't need a second "D" at the end of COMMAND.
Fixed!! Didn't notice
Thanks! Fixing it

**Comment by andresgongora** [comment]
> I made the changes to `crit_cpu_percent` and `crit_ram_percent`. When I open a new terminal, or when I directly call the script, I get;
> 
> ```
> SYSTEM LOAD:   3.1 us   6.2 sy   0.0 ni  90.6 id  
>   PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
>  2312 root      20   0  591088  76928  46608 S   6.2   2.0   0:04.05 Xorg
>  2513 steve     20   0  539992  36720  29644 S   6.2   0.9   0:00.37 panel-1-p+
>  2517 steve     20   0  218984  27160  22104 S   6.2   0.7   0:00.13 panel-2-b+
> 
> MEMORY:	 Only 3152 MB of RAM available!!
>     %	 SIZE	  PID	COMMANDD
>   1.9    81MB    2312	/usr/lib/xorg/Xorg
>   1.5    53MB    2548	/usr/bin/python3
>   1.1    39MB    2511	nm-applet
> ```

Ahh ok. I see. Hmmm
That means that the bug is somewhere in `print-utils.sh`. Let me take a look at the script and reason about the most likely cause.

**Comment by andresgongora** [comment]
[a while later]

Oh man. I really want to fix this bug. But it's so weird I don't even know where to start.
I think the most likely cause is that the `print_cols_max` protection is kicking in. It is meant to NOT print anything if the terminal is not wide enough to actually show it. Is your terminal very small? If you add `tput cols` at the end of your bashrc file, what value do you see? 

[another while later]

Ok, I've pushed a new version to the develop branch. Please reinstall it like last time. Now, if the terminal is too small, it will warn you with a message along the lines of _synth-shell status.sh does not fit in the current terminal..._

**Comment by slink007** [comment]
With the newest development build I see the following when opening a terminal.
`synth-shell status.sh does not fit in the current terminal...`

**Comment by andresgongora** [comment]
> With the newest development build I see the following when opening a terminal.
> `synth-shell status.sh does not fit in the current terminal...`

Ok!! We are getting very close to the source of the problem. How wide is your terminal?

**Comment by slink007** [comment]
I feel sure that we're running into this problem due to the length of the GPU string.  If I comment that out in the config file I get perfect output no matter when or how I call the script.

**Comment by slink007** [comment]
Default is 80 col x 24 row.  Nothing special about those settings.  It just came that way when I installed the OS.

**Comment by andresgongora** [comment]
> I feel sure that we're running into this problem due to the length of the GPU string. If I comment that out in the config file I get perfect output no matter when or how I call the script.

I added extra code to "trim" your GPU name. Is it still too long? Please, post the current name here and I'll add extra filters to keep short yet accurate

**Comment by andresgongora** [comment]
I just pushed to develop a ton of extra filters to prevent the GPU name from becoming too long. If you don't mind, test it :)
It's in the develop branch.

**Comment by andresgongora** [comment]
I've created #129. If the problem is solved, please let me know and I will merge the fix into master. If however, there is still some fine tuning to be done, please let me know. There's no hurry :)

**Comment by slink007** [comment]
Sorry to let this go so long.  Work has been crazy and I'm just now finding the time to return to this issue.

I did a pull from master because, as I read things, you merged the changes in there.  I do see that the GPU output has been shortened.  I still don't see the image when I open up a new terminal and it comes up with the default size that I listed earlier.  If I change the defaults to make the terminal wider then the image is shown.

**Comment by andresgongora** [comment]
Don't worry. Work is work, and a hobby is a hobby.

Hmm I'm sad to hear that. I run some simulation's with your GPU name and I thought I had shortened it enough. Do you mind posting a new screenshot? Or alternatively simply the strings for your GUs (because your system has two, right?).

I'll try to fix it. Worst case, I'll add a fallback mechanism that force-trims the GPU name's if they are too long.

**Comment by slink007** [comment]
![Screenshot_2019-07-25_15-38-17](https://user-images.githubusercontent.com/41128914/61903743-4508c780-aef3-11e9-98c5-edf7447ceb35.png)
Even with the GPU text shortened I think that the default dimensions are just too small to show both the image and the text side-by-side.

**Comment by andresgongora** [comment]
Thanks!
Ok. The AMD one looks sexy now. But I have to do something about the intel one.
How about I rename it to `Intel Mobile 4 IC`. Yeah, that sounds about right. Pushing to develop and then mergin into master.

**Comment by andresgongora** [comment]
Done! You can safely pull from master!
Please let me know if it worked :)

**Comment by slink007** [comment]
Pulled from master and did the install.  The Intel line looks identical to the way that it did before.

**Comment by andresgongora** [comment]
That should not have happened... Checking...

**Comment by andresgongora** [comment]
Weird. Line 398 of `status.sh` replaces `Integrated Controller` with `IC`. I don't know what I did wrong. Could you check if the line `s/Integrated Controller/IC/g;` is contained in `~/.config/synth-shell/status.sh`? If it is, open a new terminal and confirm that the problem persists.

**Comment by andresgongora** [comment]
I've pushed a new change to master. In case the order matters.

**Comment by andresgongora** [comment]
It seems to work now, right? Please reopen if needed ;)
